In [ ]:
import pandas as pd

df = pd.read_csv("./data/DSI_kickstarterscrape_dataset.csv", encoding="latin-1")

print("Number of rows", len(df))
df.head()

Number of rows 45957

,project id,name,url,category,subcategory,location,status,goal,pledged,funded percentage,backers,funded date,levels,reward levels,updates,comments,duration
0,39409,WHILE THE TREES SLEEP,http://www.kickstarter.com/projects/emiliesaba...,Film & Video,Short Film,"Columbia, MO",successful,10500.0,11545.0,1.099524,66,"Fri, 19 Aug 2011 19:28:17 -0000",7,"$25,$50,$100,$250,$500,$1,000,$2,500",10,2,30.00
1,126581,Educational Online Trading Card Game,http://www.kickstarter.com/projects/972789543/...,Games,Board & Card Games,"Maplewood, NJ",failed,4000.0,20.0,0.005000,2,"Mon, 02 Aug 2010 03:59:00 -0000",5,"$1,$5,$10,$25,$50",6,0,47.18
2,138119,STRUM,http://www.kickstarter.com/projects/185476022/...,Film & Video,Animation,"Los Angeles, CA",live,20000.0,56.0,0.002800,3,"Fri, 08 Jun 2012 00:00:31 -0000",10,"$1,$10,$25,$40,$50,$100,$250,$1,000,$1,337,$9,001",1,0,28.00
3,237090,GETTING OVER - One son's search to finally kno...,http://www.kickstarter.com/projects/charnick/g...,Film & Video,Documentary,"Los Angeles, CA",successful,6000.0,6535.0,1.089167,100,"Sun, 08 Apr 2012 02:14:00 -0000",13,"$1,$10,$25,$30,$50,$75,$85,$100,$110,$250,$500...",4,0,32.22
4,246101,The Launch of FlyeGrlRoyalty &quot;The New Nam...,http://www.kickstarter.com/projects/flyegrlroy...,Fashion,Fashion,"Novi, MI",failed,3500.0,0.0,0.000000,0,"Wed, 01 Jun 2011 15:25:39 -0000",6,"$10,$25,$50,$100,$150,$250",2,0,30.00

In [11]:
# Answering Question 1
# What is the mean (total) pledge that projects get? (not per backer)
# Your answer may vary by +/- 5%

In [18]:
# First Step: Let's clean the data of the 'pledged' column and remove any non-numeric values

pledged_df = df.copy()

# Remove any non-numeric values
pledged_df['pledged'] = pledged_df['pledged'].apply(lambda x: x if isinstance(x, (int, float)) else None)

# Drop rows where 'pledged' is None/NaN
pledged_df = pledged_df.dropna(subset=['pledged'])

print("Number of rows after removing non-numeric values: ", len(pledged_df))

Number of rows after removing non-numeric values:  45945

In [ ]:
# Seconds Step: Check if all project ids are unique

print("Are all project ids unique? ", pledged_df["project id"].nunique() == len(pledged_df["project id"]))

Are all project ids unique?  False

In [29]:
print("Number of duplicated rows: ", pledged_df["project id"].duplicated().sum())

Number of duplicated rows:  142

In [30]:
pledged_df[pledged_df["project id"].duplicated(keep=False)].sort_values("project id")

,project id,name,url,category,subcategory,location,status,goal,pledged,funded percentage,backers,funded date,levels,reward levels,updates,comments,duration
45651,2140333236,Imagined Family Heirlooms: An Archive of Inher...,http://www.kickstarter.com/projects/andersonst...,Photography,Photography,"Little Rock, AR",successful,5800.0,8521.0,1.469138,110,"Fri, 29 Jul 2011 00:53:53 -0000",16,"$10,$20,$35,$50,$75,$100,$150,$200,$225,$300,$...",5,4,67.00
45652,2140333236,Imagined Family Heirlooms: An Archive of Inher...,http://www.kickstarter.com/projects/andersonst...,Photography,Photography,"Little Rock, AR",successful,5800.0,8521.0,1.469138,110,"Fri, 29 Jul 2011 00:53:53 -0000",16,"$10,$20,$35,$50,$75,$100,$150,$200,$225,$300,$...",5,4,67.00
45653,2140344109,Help Fund Thana Alexa's Debut Album &quot;Ode ...,http://www.kickstarter.com/projects/1024906052...,Music,Jazz,"New York, NY",successful,15000.0,16678.0,1.111867,142,"Sun, 20 May 2012 20:36:57 -0000",16,"$1,$5,$10,$15,$25,$50,$75,$100,$200,$250,$300,...",5,2,32.00
45654,2140344109,Help Fund Thana Alexa's Debut Album &quot;Ode ...,http://www.kickstarter.com/projects/1024906052...,Music,Jazz,"New York, NY",successful,15000.0,16678.0,1.111867,142,"Sun, 20 May 2012 20:36:57 -0000",16,"$1,$5,$10,$15,$25,$50,$75,$100,$200,$250,$300,...",5,2,32.00
45655,2140513451,The Cookie Chew - Changing the Way We Eat a Co...,http://www.kickstarter.com/projects/1650956569...,Food,Food,"San Diego, CA",successful,4500.0,5540.0,1.231111,89,"Tue, 24 Aug 2010 04:43:00 -0000",5,"$10,$50,$75,$100,$500",14,17,43.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45930,2146435917,Making Mama(s) Proud: The 2011 &quot;Donna/Mad...,http://www.kickstarter.com/projects/johnpaulka...,Theater,Theater,"Los Angeles, CA",successful,5000.0,5390.0,1.078000,86,"Sat, 04 Jun 2011 08:56:58 -0000",8,"$1,$10,$25,$50,$100,$200,$500,$1,000",5,1,30.00
45931,2146437406,The Production of Erasure,http://www.kickstarter.com/projects/295025953/...,Photography,Photography,"Brooklyn, NY",successful,1200.0,1220.0,1.016667,17,"Thu, 03 Mar 2011 04:09:38 -0000",6,"$15,$25,$50,$100,$200,$500",1,0,30.00
45932,2146437406,The Production of Erasure,http://www.kickstarter.com/projects/295025953/...,Photography,Photography,"Brooklyn, NY",successful,1200.0,1220.0,1.016667,17,"Thu, 03 Mar 2011 04:09:38 -0000",6,"$15,$25,$50,$100,$200,$500",1,0,30.00
45933,2146534146,CALLING on ANGELS - not FOR KIDS ONLY!,http://www.kickstarter.com/projects/callingona...,Film &amp; Video,Film &amp; Video,"Burbank, CA",failed,10000.0,250.0,0.025000,1,"Sat, 10 Sep 2011 19:00:47 -0000",11,"$10,$25,$50,$75,$100,$150,$250,$500,$1,000,$1,...",0,0,60.00
45934,2146534146,CALLING on ANGELS - not FOR KIDS ONLY!,http://www.kickstarter.com/projects/callingona...,Film & Video,Film &amp; Video,"Burbank, CA",failed,10000.0,250.0,0.025000,1,"Sat, 10 Sep 2011 19:00:47 -0000",11,"$10,$25,$50,$75,$100,$150,$250,$500,$1,000,$1,...",0,0,60.00

In [35]:
# Step 3: Dropping duplicated rows
pledged_df = pledged_df.drop_duplicates(subset=["project id"])

print("Number of rows after dropping duplicated rows: ", len(pledged_df))

Number of rows after dropping duplicated rows:  45803

In [38]:
# Check again if all project ids are unique
print("Are all project ids unique? ", pledged_df["project id"].nunique() == len(pledged_df["project id"]))
print("Number of duplicated rows: ", pledged_df["project id"].duplicated().sum())
pledged_df[pledged_df["project id"].duplicated(keep=False)]

Are all project ids unique?  True
Number of duplicated rows:  0

Empty DataFrame
Columns: [project id, name, url, category, subcategory, location, status, goal, pledged, funded percentage, backers, funded date, levels, reward levels, updates, comments, duration]
Index: []

In [37]:
# Step 4: Calculate the mean pledge

mean_pledged = pledged_df['pledged'].mean()

print("Mean pledge: ", mean_pledged)

Mean pledge:  4985.739165556841